// <auto-generated />
using System;
using Magma3.NotaFiscal.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Magma3.NotaFiscal.Infra.Data.Migrations
{
    [DbContext(typeof(NotaFiscalDbContext))]
    partial class NotaFiscalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Magma3.NotaFiscal.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cod_cliente");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("nome_cliente");

                    b.Property<Guid>("UId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uid_cliente");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.ToTable("tb_cliente", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeCliente = "Cliente 1",
                            UId = new Guid("c5b456a8-e507-46bf-b73a-cf83f3016555")
                        },
                        new
                        {
                            Id = 2,
                            NomeCliente = "Cliente 2",
                            UId = new Guid("3c11c144-0fb3-4e12-94a5-beda4bc588a4")
                        },
                        new
                        {
                            Id = 3,
                            NomeCliente = "Cliente 3",
                            UId = new Guid("b10b55f3-3f60-4b14-856a-77ad6236bfad")
                        });
                });

            modelBuilder.Entity("Magma3.NotaFiscal.Domain.Entities.NotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cod_nota_fiscal");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("chave_acesso_nota_fiscal");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("fk_cod_cliente");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime")
                        .HasColumnName("data_emissao_nota_fiscal");

                    b.Property<string>("NumeroNota")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("numero_nota_fiscal");

                    b.Property<Guid>("UId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uid_nota_fiscal");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ClienteId");

                    b.ToTable("tb_nota_fiscal", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChaveAcesso = "84815641816",
                            ClienteId = 1,
                            DataEmissao = new DateTime(2023, 5, 1, 18, 17, 52, 569, DateTimeKind.Local).AddTicks(7278),
                            NumeroNota = "12346578415",
                            UId = new Guid("6ab1f13a-efcf-4ee6-9bbe-28bcd89c7714")
                        },
                        new
                        {
                            Id = 2,
                            ChaveAcesso = "32433241816",
                            ClienteId = 2,
                            DataEmissao = new DateTime(2023, 5, 1, 18, 17, 52, 569, DateTimeKind.Local).AddTicks(7291),
                            NumeroNota = "12346578415",
                            UId = new Guid("320b47ac-512d-4fe4-9203-7f4850df76ad")
                        },
                        new
                        {
                            Id = 3,
                            ChaveAcesso = "67545634636",
                            ClienteId = 3,
                            DataEmissao = new DateTime(2023, 5, 1, 18, 17, 52, 569, DateTimeKind.Local).AddTicks(7293),
                            NumeroNota = "12341231231",
                            UId = new Guid("f216a845-91e4-4371-9ae5-78d441c4d793")
                        });
                });

            modelBuilder.Entity("Magma3.NotaFiscal.Domain.Entities.NotaFiscalProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cod_nota_fiscal_produto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("datetime")
                        .HasColumnName("data_compra_produto");

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("int")
                        .HasColumnName("fk_nota_fiscal");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int")
                        .HasColumnName("fk_produto");

                    b.Property<decimal>("ProdutoPreco")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_produto");

                    b.Property<Guid>("UId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uid_nota_fiscal_produto");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("NotaFiscalId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("tb_nota_fiscal_produto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCompra = new DateTime(2023, 5, 1, 18, 17, 52, 569, DateTimeKind.Local).AddTicks(9569),
                            NotaFiscalId = 1,
                            ProdutoId = 1,
                            ProdutoPreco = 99.99m,
                            UId = new Guid("dc874688-6b8e-4406-801d-d069c56be22a")
                        },
                        new
                        {
                            Id = 2,
                            DataCompra = new DateTime(2023, 5, 1, 18, 17, 52, 569, DateTimeKind.Local).AddTicks(9617),
                            NotaFiscalId = 2,
                            ProdutoId = 2,
                            ProdutoPreco = 55.99m,
                            UId = new Guid("ea24fc65-d979-48a2-9cdf-00035e0265dd")
                        },
                        new
                        {
                            Id = 3,
                            DataCompra = new DateTime(2023, 5, 1, 18, 17, 52, 569, DateTimeKind.Local).AddTicks(9619),
                            NotaFiscalId = 3,
                            ProdutoId = 3,
                            ProdutoPreco = 88.00m,
                            UId = new Guid("21257742-fa03-47c7-97d8-c8622e3d6e39")
                        });
                });

            modelBuilder.Entity("Magma3.NotaFiscal.Domain.Entities.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cod_produto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("des_produto");

                    b.Property<decimal>("ProdutoPreco")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("preco_produto");

                    b.Property<Guid>("UId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uid_produto");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.ToTable("tb_produto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descricao = "Produto Teste 1",
                            ProdutoPreco = 99.99m,
                            UId = new Guid("3df3c297-a4bc-475c-95d6-c1bbc0392d18")
                        },
                        new
                        {
                            Id = 2,
                            Descricao = "Produto Teste 2",
                            ProdutoPreco = 55.99m,
                            UId = new Guid("ded68003-42ee-4c78-9e3c-00363f1fa90a")
                        },
                        new
                        {
                            Id = 3,
                            Descricao = "Produto Teste 3",
                            ProdutoPreco = 88.00m,
                            UId = new Guid("e3018670-fdd5-4682-9d81-45d6126932c3")
                        });
                });

            modelBuilder.Entity("Magma3.NotaFiscal.Domain.ValueObjects.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cod_contato");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CelularNumero")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("celular_numero");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("fk_cod_cliente");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("tb_contato", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CelularNumero = "51998915689",
                            ClienteId = 1
                        },
                        new
                        {
                            Id = 2,
                            CelularNumero = "51995674356",
                            ClienteId = 2
                        },
                        new
                        {
                            Id = 3,
                            CelularNumero = "51876785678",
                            ClienteId = 3
                        });
                });

            modelBuilder.Entity("Magma3.NotaFiscal.Domain.ValueObjects.Endereco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cod_endereco");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cep");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("varchar(70)")
                        .HasColumnName("cidade");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int")
                        .HasColumnName("fk_cod_cliente");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasColumnType("varchar(200)")
                        .HasColumnName("logradouro");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(10)")
                        .HasColumnName("endereco_numero");

                    b.Property<string>("UF")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("uf");

                    b.HasKey("Id");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("Id"));

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("tb_endereco", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bairro = "Centro Histórico",
                            Cep = "900200004",
                            Cidade = "PORTO ALEGRE",
                            ClienteId = 1,
                            Logradouro = "Rua dos Andradas",
                            Numero = "771",
                            UF = "RS"
                        },
                        new
                        {
                            Id = 2,
                            Bairro = "Centro Histórico",
                            Cep = "900200004",
                            Cidade = "PORTO ALEGRE",
                            ClienteId = 2,
                            Logradouro = "Rua dos Andradas",
                            Numero = "234",
                            UF = "RS"
                        },
                        new
                        {
                            Id = 3,
                            Bairro = "Centro Histórico",
                            Cep = "900200004",
                            Cidade = "PORTO ALEGRE",
                            ClienteId = 3,
                            Logradouro = "Rua dos Andradas",
                            Numero = "534",
                            UF = "RS"
                        });
                });

            modelBuilder.Entity("Magma3.NotaFiscal.Domain.Entities.NotaFiscal", b =>
                {
                    b.HasOne("Magma3.NotaFiscal.Domain.Entities.Cliente", "Cliente")
                        .WithMany("NotaFiscais")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Magma3.NotaFiscal.Domain.Entities.NotaFiscalProduto", b =>
                {
                    b.HasOne("Magma3.NotaFiscal.Domain.Entities.NotaFiscal", "NotaFiscal")
                        .WithMany("Produtos")
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Magma3.NotaFiscal.Domain.Entities.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NotaFiscal");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Magma3.NotaFiscal.Domain.ValueObjects.Contato", b =>
                {
                    b.HasOne("Magma3.NotaFiscal.Domain.Entities.Cliente", "Cliente")
                        .WithOne("Celular")
                        .HasForeignKey("Magma3.NotaFiscal.Domain.ValueObjects.Contato", "ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Magma3.NotaFiscal.Domain.ValueObjects.Endereco", b =>
                {
                    b.HasOne("Magma3.NotaFiscal.Domain.Entities.Cliente", "Cliente")
                        .WithOne("Endereco")
                        .HasForeignKey("Magma3.NotaFiscal.Domain.ValueObjects.Endereco", "ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("Magma3.NotaFiscal.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Celular");

                    b.Navigation("Endereco");

                    b.Navigation("NotaFiscais");
                });

            modelBuilder.Entity("Magma3.NotaFiscal.Domain.Entities.NotaFiscal", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
